// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_assissignment;

#nullable disable

namespace Web_assissignment.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20241230091725_initial_create")]
    partial class initial_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_assissignment.Models.Projectt", b =>
                {
                    b.Property<int>("Project_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Project_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("End_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Project_id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Project_id = 1,
                            Description = "Web application project 1",
                            End_date = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Web Application",
                            Start_date = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Project_id = 2,
                            Description = "Web application complete the cotent",
                            End_date = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Web Application Content",
                            Start_date = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Web_assissignment.Models.Taskk", b =>
                {
                    b.Property<int>("Task_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Task_id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Project_id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamMember_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Task_id");

                    b.HasIndex("Project_id");

                    b.HasIndex("TeamMember_id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Task_id = 1,
                            Deadline = new DateTime(2024, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Developing the web application ",
                            Priority = "High",
                            Project_id = 1,
                            Status = "Completed",
                            TeamMember_id = 1,
                            Title = "Developing"
                        },
                        new
                        {
                            Task_id = 2,
                            Deadline = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make Penetration Testing",
                            Priority = "High",
                            Project_id = 1,
                            Status = "In Progress",
                            TeamMember_id = 1,
                            Title = "Penetration Testing"
                        },
                        new
                        {
                            Task_id = 3,
                            Deadline = new DateTime(2024, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fill Content of the website",
                            Priority = "Low",
                            Project_id = 1,
                            Status = "Pending",
                            TeamMember_id = 1,
                            Title = "Fill Content"
                        },
                        new
                        {
                            Task_id = 4,
                            Deadline = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Security Consulting tips",
                            Priority = "Medium",
                            Project_id = 1,
                            Status = "Pending",
                            TeamMember_id = 1,
                            Title = "Security Consulting"
                        });
                });

            modelBuilder.Entity("Web_assissignment.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMember_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMember_id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TeamMember_id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            TeamMember_id = 1,
                            Email = "Nour@gmail.com",
                            Name = "Nour",
                            Role = "Web Pentester"
                        },
                        new
                        {
                            TeamMember_id = 2,
                            Email = "Hamsa@gmail.com",
                            Name = "Hamsa",
                            Role = "Developer"
                        },
                        new
                        {
                            TeamMember_id = 3,
                            Email = "Wasfy@gmail.com",
                            Name = "Wasfy",
                            Role = "Researcher"
                        });
                });

            modelBuilder.Entity("Web_assissignment.Models.Taskk", b =>
                {
                    b.HasOne("Web_assissignment.Models.Projectt", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("Project_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Web_assissignment.Models.TeamMember", "TeamMember")
                        .WithMany("Tasks")
                        .HasForeignKey("TeamMember_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Web_assissignment.Models.Projectt", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Web_assissignment.Models.TeamMember", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
